apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }} 
  labels:
    mode: deploy
spec:
  selector:
    app.kubernetes.io/name: broadcast-service
  ports:
    - protocol: TCP
      port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  type: ClusterIP