# bash
helm install nginx-ingress-controller bitnami/nginx-ingress-controller \
--namespace traffic \
--values https://starci-lab.github.io/cifarm-k8s/values/nginx-ingress-controller-values.yaml
```
Create file `cert-manager-values.yaml`
```yaml
# cert-manager-values.yaml

# Resources for the cainjector component
cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 200Mi

# Resources for the controller component
controller:
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 200Mi

# Resources for the webhook component
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 200Mi