# Jenkins configuration
jenkinsUser: "admin"
replicaCount: 5
jenkinsPassword: "Cuong123_A"
# Persistence configuration
persistence:
  enabled: true
  size: 10Gi

# Resource requests and limits
resources:
  requests:
    cpu: "30m"
    memory: "60Mi"
  limits:
    cpu: "90m"
    memory: "180Mi"
tls:
  resources:
    requests:
      cpu: "30m"
      memory: "60Mi"
    limits:
      cpu: "90m"
      memory: "180Mi"

# Service configuration
service:
  type: ClusterIP

plugins: [
  "aws-credentials",
  "kubernetes",
]