# kafka-values.yaml

# Namespace for the Kafka deployment
namespace: brokers

# Kafka listeners configuration
listeners:
  client:
    protocol: "PLAINTEXT"  # Protocol for client communication
  controller:
    protocol: "PLAINTEXT"  # Protocol for controller communication

# Kafka controller resource requests and limits
controller:
  resources:
    requests:
      cpu: "20m"          # Minimum CPU requested for the controller (20 millicores)
      memory: "40Mi"      # Minimum memory requested for the controller (40 MiB)
    limits:
      cpu: "200m"         # Maximum CPU allowed for the controller (200 millicores)
      memory: "400Mi"     # Maximum memory allowed for the controller (400 MiB)