# redis-values.yaml

# Disable authentication for Redis
auth:
  enabled: false

# Redis replica configuration
replica:
  replicaCount: 1
  resources:
    requests:
      cpu: "10m"               # CPU request for Redis replica (10 millicores)
      memory: "20Mi"           # Memory request for Redis replica (20 MiB)
    limits:
      cpu: "100m"              # CPU limit for Redis replica (100 millicores)
      memory: "200Mi"          # Memory limit for Redis replica (200 MiB)

# Redis master configuration
master:
  resources:
    requests:
      cpu: "20m"               # CPU request for Redis master (20 millicores)
      memory: "40Mi"           # Memory request for Redis master (40 MiB)
    limits:
      cpu: "200m"              # CPU limit for Redis master (200 millicores)
      memory: "400Mi"          # Memory limit for Redis master (400 MiB)