# this file is used to create a postgres master-slave setup for cifarm server
version: "3"
services:
  redis-master:
    image: bitnami/redis:latest
    restart: always
    env_file:
      - ../../../../.env.local
    ports:
      - 6379:6379
    volumes:
      - redis:/cifarm/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
  redis-slave-1:
    image: bitnami/redis:latest
    restart: always
    env_file:
      - ../../../../.env.local
    depends_on:
      - redis-master
    environment:
      - REDIS_MASTER_HOST=host.docker.internal
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6380:6379
volumes:
  redis:
    driver: local

#docker compose -f .\pods\pre-built\redis\example\docker.example.yaml up --build -d