
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifarm-mongodb-primary-persistent-volume
  namespace: default
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: cifarm-mongodb-primary-storage-class
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/volumes/cifarm-mongodb-primary" 
    type: DirectoryOrCreate