
# SPDX-License-Identifier: MIT

annotations:
  category: Service
  licenses: MIT
apiVersion: v1
appVersion: 1.0.0
description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
home: N/A
icon: N/A
keywords:
- service
maintainers:
- name: CiLab 2.0
  url: ""
name: service
version: 1.0.2
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
