---
# Source: service/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-service
  namespace: default
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
automountServiceAccountToken: false
---
# Source: service/templates/env-vars-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-service-env-vars
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
type: Opaque
stringData:
  FOO3: bar
  FOO4: bar2
---
# Source: service/templates/env-vars-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-service-env-vars
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
data:
  FOO: bar
  FOO2: bar2
---
# Source: service/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-service
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
---
# Source: service/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-service
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-service
subjects:
  - kind: ServiceAccount
    name: release-name-service
    namespace: "default"
---
# Source: service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-service
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 8080
      protocol: TCP
      targetPort: app
      nodePort: null
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: service
    app.kubernetes.io/component: service
---
# Source: service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-service
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: service-1.0.5
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: service
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: service
        app.kubernetes.io/version: 1.0.0
        helm.sh/chart: service-1.0.5
        app.kubernetes.io/component: service
      annotations:
        checksum/env-vars-secrets: 28eddab85fdc88b05eddad6bbdac5445bf2af9ef3fbcbcac60b27110497b2ffa
        checksum/env-vars-configmap: 4b78d57473047cde93595bbe6c469ce5e711457fb220888d67afeb6bf58efa4f
    spec:
      serviceAccountName: release-name-service
      
      automountServiceAccountToken: 
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/name: service
                    app.kubernetes.io/component: service
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      containers:
        - name: service
          image: docker.io/cifarm/gameplay-service:latest
          imagePullPolicy: "Always"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              value: "default"
          envFrom:
            - configMapRef:
                name: release-name-service-env-vars
            - secretRef:
                name: release-name-service-env-vars
          ports:
            - containerPort: 8080
              name: app
              protocol: TCP
            - containerPort: 8081
              name: health-check
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: app
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: health-check
            initialDelaySeconds: 
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: 90m
              memory: 180Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
      volumes:
