apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-sc-pvc
  namespace: default

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi