apiVersion: v1
kind: Pod
metadata:
  name: kaniko-pod
  labels:
    app: kaniko
spec:
  containers:
  - name: kaniko
    image: bitnami/kaniko:latest  # Kaniko image
    command:
      - "/busybox/sleep"  # Use a dummy command to keep the container running
    args:
      - "3600"  # Sleep for an hour
  restartPolicy: Never  # Don't restart the pod once the job is done

  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret  # Secret name containing Docker registry credentials
