# ClusterIP configuration
clusterIp:
  metadata:
    name: gameplay-service-cluster-ip
  selector:
    name: gameplay-service-selector

# Secret configuration
secret:
  metadata:
    name: gameplay-service-secret
  env:
    jwt:
      secret: "C3ZofmtZ+hXQF2d~&bBu9x'UtkUyz?)MwXiXy_eGFlyO|:v!JW$?iZ&U6:kPQg("
      accessTokenExpiration: "5m"
      refreshTokenExpiration: "7d"
    gameplayPostgres:
      dbName: "postgres"
      host: "postgres"
      port: 5432
      user: "postgres"
      pass: "postgres"
    gameplayTestPostgres:
      dbName: "postgres"
      host: "postgres"
      port: 5432
      user: "postgres"
      pass: "postgres"
    redis:
      ttl: 86400000
      cache:
        host: "redis"
        port: 6379
      adapter:
        host: "redis"
        port: 6379
      job:
        host: "redis"
        port: 6379
    kafka:
      broker1:
        host: "kafka"
        port: 9092
      broker2:
        host: "kafka"
        port: 9092
      broker3:
        host: "kafka"
        port: 9092
    containers:
      subgraphStaticUrl: "http://localhost:3007/graphql"
      restApiGateway:
        host: "localhost"
        port: 3001
      websocketApiGateway:
        host: "localhost"
        port: 3002
      graphqlApiGateway:
        host: "localhost"
        port: 3003
      gameplayService:
        host: "localhost"
        port: 3014

# Deployment configuration
deployment:
  metadata:
    name: gameplay-service
  args:
    image:
      repository: cifarm/gameplay-service
      tag: latest
    dockerfile: ./apps/gameplay-service/Dockerfile
    context: git://github.com/starci-lab/cifarm-containers
  replicaCount: 2
  containerPort: 
    port: 3014
    targetPort: 3014
  resources: 
    requests:
      cpu: "20m"
      memory: "40Mi"
    limits:
      cpu: "200m"
      memory: "400Mi"

# Service configuration
scaledObject:
  metadata:
    name: gameplay-service-scaled-object
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 30                   
  pollingInterval: 5     
  trigger:
    serverAddress:
      host: 
        name: prometheus-kube-prometheus-prometheus
        namespace: monitoring
      port: 9090
    metricName: gameplay-service-scaled-object_keda
    query: sum(rate(container_cpu_usage_seconds_total{namespace="monitoring", pod=~"gameplay-service-.*"}[1m]))"
    threshold: "0.3"