# this file is used to create a postgres master-3slave setup for cifarm server
version: "3"
services:
  cifarm-server-postgresql-master:
    image: postgres:latest
    restart: always
    env_file:
      - ../../.env
    ports:
      - ${POSTGRESQL_MASTER_HOST_PORT}:5432
    volumes:
      - postgresql_master_data:/cifarm-server/postgresql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  cifarm-server-postgresql-slave-1:
    image: postgres:latest
    restart: always
    env_file:
      - ../../.env
    ports:
      - 5432
    depends_on:
      - cifarm-server-postgresql-master
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_MASTER_HOST=cifarm-server-postgresql-master
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=${POSTGRESQL_MASTER_HOST_PORT}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${POSTGRESQL_MASTER_HOST} -p ${POSTGRESQL_MASTER_PORT_NUMBER}"]
      interval: 30s
      timeout: 10s
      retries: 5 
volumes:
  postgresql_master_data:
    driver: local