apiVersion: v1
kind: Pod
metadata:
  name: postgres-cluster
  labels:
    app: cifarm
spec:
  initContainers:
    # master
    - name: postgres-cluster
      image: bitnami/postgresql
      restartPolicy: Always
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5432"
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5432"
        initialDelaySeconds: 5
        periodSeconds: 5
      env:
        # POSTGRESQL_PGAUDIT_LOG
        - name: POSTGRESQL_PGAUDIT_LOG
          value: "READ,WRITE"

        # POSTGRESQL_LOG_HOSTNAME
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "true"

        # POSTGRESQL_REPLICATION_MODE
        - name: POSTGRESQL_REPLICATION_MODE
          value: "master"

        # POSTGRESQL_REPLICATION_USER
        - name: POSTGRESQL_REPLICATION_USER
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_REPLICATION_USER

        # POSTGRESQL_REPLICATION_PASSWORD
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_REPLICATION_PASSWORD

        # POSTGRESQL_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_PASSWORD
        
        # POSTGRESQL_DATABASE
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_DATABASE

        # POSTGRESQL_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_ALLOW_EMPTY_PASSWORD
      ports:
        # we cannot pass env variables to containerPort, due to limitations in k8s
        - containerPort: 5432
          name: pm # postgresql-master
      volumeMounts:
      - name: cspmv2 # cifarm-server-postgresql-master-volume2
        mountPath: /var/lib/cifarm-server-postgresql-master-volume
  
  containers:
    # slave 1
    - name: postgresql-slave-1
      image: bitnami/postgresql
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5433"
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5433"
        initialDelaySeconds: 5
        periodSeconds: 5
      env:
        # POSTGRESQL_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_PASSWORD

        # POSTGRESQL_MASTER_HOST
        - name: POSTGRESQL_MASTER_HOST
          value: "127.0.0.1"
        
        # POSTGRESQL_PGAUDIT_LOG
        - name: POSTGRESQL_PGAUDIT_LOG
          value: "READ"

        # POSTGRESQL_LOG_HOSTNAME
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "true"

        # POSTGRESQL_REPLICATION_MODE
        - name: POSTGRESQL_REPLICATION_MODE
          value: "slave"

        # POSTGRESQL_REPLICATION_USER
        - name: POSTGRESQL_REPLICATION_USER
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_REPLICATION_USER 

        # POSTGRESQL_REPLICATION_PASSWORD
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_REPLICATION_PASSWORD

        # POSTGRESQL_MASTER_PORT_NUMBER
        - name: POSTGRESQL_MASTER_PORT_NUMBER
          value: "5432"
              
        # POSTGRESQL_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_ALLOW_EMPTY_PASSWORD
        
        # POSTGRESQL_PORT_NUMBER
        - name: POSTGRESQL_PORT_NUMBER
          value: "5433"
      ports:
        # we cannot pass env variables to containerPort, due to limitations in k8s
        - containerPort: 5433 # 5543
          name: ps1 # postgresql-slave-1
      
    # slave 2
    - name: postgresql-slave-2
      image: bitnami/postgresql
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5434"
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5434"
        initialDelaySeconds: 5
        periodSeconds: 5
      env:
        # POSTGRESQL_USERNAME
        - name: POSTGRESQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_USERNAME

        # POSTGRESQL_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_PASSWORD

        # POSTGRESQL_MASTER_HOST
        - name: POSTGRESQL_MASTER_HOST
          value: "127.0.0.1"
        
        # POSTGRESQL_PGAUDIT_LOG
        - name: POSTGRESQL_PGAUDIT_LOG
          value: "READ"

        # POSTGRESQL_LOG_HOSTNAME
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "true"

        # POSTGRESQL_REPLICATION_MODE
        - name: POSTGRESQL_REPLICATION_MODE
          value: "slave"

        # POSTGRESQL_REPLICATION_USER
        - name: POSTGRESQL_REPLICATION_USER
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_REPLICATION_USER 

        # POSTGRESQL_REPLICATION_PASSWORD
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_REPLICATION_PASSWORD

        # POSTGRESQL_MASTER_PORT_NUMBER
        - name: POSTGRESQL_MASTER_PORT_NUMBER
          value: "5432"
              
        # POSTGRESQL_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-postgres-cluster
              key: POSTGRESQL_ALLOW_EMPTY_PASSWORD
        
        # POSTGRESQL_PORT_NUMBER
        - name: POSTGRESQL_PORT_NUMBER
          value: "5434"
      ports:
        # we cannot pass env variables to containerPort, due to limitations in k8s
        - containerPort: 5434 # 5544
          name: ps2 # postgresql-slave-2
  volumes:
    - name: cspmv2 # cifarm-server-postgresql-master-volume
      persistentVolumeClaim:
        claimName: cspmc2 # cifarm-server-postgresql-master-claim

# kubectl create -f ./pods//databases/cifarm-server-postgres-cluster/dev/base.yaml
# kubectl get pods
# kubectl delete pod cifarm-server-postgres-cluster
# kubectl describe pod cifarm-server-postgres-cluster -n default