apiVersion: apps/v1
kind: Deployment
metadata:
  name: cifarm-server-deployment
  labels:
    app: cifarm-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cifarm-server
  template:
    metadata:
      labels:
        app: cifarm-server
    spec:
      containers:
      - name: cifarm-server
        image: starci/cifarm-server
        env:
          - name: NAKAMA_DATABASE_ADDRESS
            value: "postgres:f8VrfNRfso@10.244.0.3:5432/postgres"
          - name: NAKAMA_CONFIG
            value: "/nakama/data/local.yml"
        command: ["/bin/sh", "-ecx"]
        args:
          - >
            /nakama/nakama migrate up --database.address $(NAKAMA_DATABASE_ADDRESS) &&
            exec /nakama/nakama --config $(NAKAMA_CONFIG) --database.address $(NAKAMA_DATABASE_ADDRESS)
        readinessProbe:
          exec:
            command: ["/nakama/nakama", "healthcheck"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        ports:
        - containerPort: 7349
        - containerPort: 7350
        - containerPort: 7351