{{- if and .Values.rbac.enabled .Values.rbac.useClusterScope }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
{{- range .Values.rbac.roles }}
  - apiGroups:
      {{- range .apiGroups }}
      - {{ . }}
      {{- end }}
    resources:
      {{- range .resources }}
      - {{ . }}
      {{- end }}
    verbs:
      {{- range .verbs }}
      - {{ . }}
      {{- end }}
{{- end }}
{{- end }}