apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-gateway-deployment
  labels:
    app.kubernetes.io/name: rest-api-gateway
    mode: deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rest-api-gateway
  template:
    metadata:
      labels:
        app: rest-api-gateway
    spec:
      containers:
        - name: rest-api-gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: rest-api-gateway-env
          ports:
            - containerPort: 3001
