apiVersion: v1
kind: Service
metadata:
  name: rest-api-gateway-node-port
  labels:
    mode: test
spec:
  selector:
    app.kubernetes.io/name: rest-api-gateway
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30123