apiVersion: v1
kind: Service
metadata:
  name: rest-api-gateway-node-port
  labels:
    mode: test
spec:
  selector:
    app.kubernetes.io/name: rest-api-gateway
  type: NodePort
  ports:
    - port:  {{ .Values.containerPort }}
      targetPort:  {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}