apiVersion: v1
kind: Service
metadata:
  name: websocket-api-gateway-load-balancer
  labels:
    mode: deploy
spec:
  selector:
    app.kubernetes.io/name: websocket-api-gateway
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  type: LoadBalancer

#kubectl exec -it websocket-api-gateway-deployment-69c895dbfd-vwlfv -- netstat -tuln