apiVersion: v1
kind: Service
metadata:
  name: websocket-api-gateway-node-port
  labels:
    mode: test
spec:
  selector:
    app.kubernetes.io/name: websocket-api-gateway
  type: NodePort
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}