apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.clusterName }}-deployment
  namespace: {{ .Values.metadata.namespace }}
  labels:
    mode: deploy
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.metadata.clusterName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.metadata.clusterName }}
    spec:
      containers:
        - name: {{ .Values.metadata.clusterName }}
          image: {{ .Values.build.image.repository }}:{{ .Values.build.image.tag }}
          resources:
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
          envFrom:
            - secretRef:
                name: {{ .Values.deployment.envSecret }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
