apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-deployment
  namespace: {{ .Values.metadata.namespace }}
  labels:
    mode: deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: {{ .Values.build.image.repository }}:{{ .Values.build.image.tag }}
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: wallet-service-env
          ports:
            - containerPort: {{ .Values.containerPort }}