apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.metadata.clusterName }}-kaniko-build
  namespace: {{ .Values.buildNamespace }}
  labels:
    mode: build
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      args:
        - "--context={{ .Values.build.context }}"
        - "--destination={{ .Values.build.image.repository }}:{{ .Values.build.image.tag }}"
        - "--dockerfile={{ .Values.build.dockerfile }}"
      resources:
        limits:
          cpu: {{ .Values.build.resources.limits.cpu }}
          memory: {{ .Values.build.resources.limits.memory }}
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
