# this file is used to create a postgres master-slave setup for cifarm server
version: "3"
services:
  cifarm-server-postgresql-master:
    image: bitnami/postgresql
    restart: always
    env_file:
      - ../../.env.local
    ports:
      - ${POSTGRESQL_MASTER_PORT}:5432
    volumes:
      - postgresql_master_data:/cifarm-server/postgresql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - ALLOW_EMPTY_PASSWORD=${POSTGRESQL_ALLOW_EMPTY_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  common-slave: &common-slave
    image: bitnami/postgresql
    restart: always
    env_file:
      - ../../.env.local
    depends_on:
      - cifarm-server-postgresql-master
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_MASTER_HOST=host.docker.internal
      - POSTGRESQL_PGAUDIT_LOG=READ
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=starci
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_MASTER_PORT_NUMBER=${POSTGRESQL_MASTER_PORT}
      - ALLOW_EMPTY_PASSWORD=${POSTGRESQL_ALLOW_EMPTY_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  cifarm-server-postgresql-slave-1:
    <<: *common-slave
    ports:
      - ${POSTGRESQL_SLAVE_PORT_1}:5432

  # Use the following block to add more slaves
  # cifarm-server-postgresql-slave-2:
  #   <<: *common-slave
  #   ports:
  #     - ${POSTGRESQL_SLAVE_PORT_2}:5432

  # cifarm-server-postgresql-slave-3:
  #   <<: *common-slave
  #   ports:
  #     - ${POSTGRESQL_SLAVE_PORT_3}:5432

  # cifarm-server-postgresql-slave-4:
  #   <<: *common-slave
  #   ports:
  #     - ${POSTGRESQL_SLAVE_PORT_4}:5432

  # cifarm-server-postgresql-slave-5:
  #   <<: *common-slave
  #   ports:
  #     - ${POSTGRESQL_SLAVE_PORT_5}:5432
  
volumes:
  postgresql_master_data:
    driver: local

# Test compose command
# docker compose -f .\databases\postgres\cifarm-server.yaml up --build -d