apiVersion: v1
entries:
  cron-worker-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9113928+07:00"
    description: N/A
    digest: 665bb7307c41ae2209761eacb0b1d2671d00151270bb487a278326cd53fbf671
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-worker-build
    urls:
    - packages/cron-worker-build-1.0.0.tgz
    version: 1.0.0
  cron-worker-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9119105+07:00"
    description: N/A
    digest: 2ca110a42a66265a5550f4d6389f51e382aa77c6eea19f9d0193f4459ea718e2
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-worker-deployment
    urls:
    - packages/cron-worker-deployment-1.0.0.tgz
    version: 1.0.0
  gameplay-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9124463+07:00"
    description: N/A
    digest: 6619133ea956bb02b6b08a1cb3018027799ccb8486f298c695da2cdfb8b16bd2
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: gameplay-service-build
    urls:
    - packages/gameplay-service-build-1.0.0.tgz
    version: 1.0.0
  gameplay-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9135257+07:00"
    description: N/A
    digest: 909ae52636355d3f877f2ae6f775bb7a88840d65a81dc1965ce1e31ccd50c425
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: gameplay-service-deployment
    urls:
    - packages/gameplay-service-deployment-1.0.0.tgz
    version: 1.0.0
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9140365+07:00"
    description: N/A
    digest: 82c4b5edccffdb58b0338e9d8a105f7af2f44aed14c42e042fc1d7c53bf9f829
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
  rest-api-gateway-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9145452+07:00"
    description: N/A
    digest: 23c67f8a658361da9f841490cd8666f324f2662da0c344053ec6a62ba5c98816
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: rest-api-gateway-build
    urls:
    - packages/rest-api-gateway-build-1.0.0.tgz
    version: 1.0.0
  rest-api-gateway-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.915064+07:00"
    description: N/A
    digest: 8fb59c7ca634adf5fcc6d55eaa1e42641cb238b43fbc5654baf5a33773708336
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: rest-api-gateway-deployment
    urls:
    - packages/rest-api-gateway-deployment-1.0.0.tgz
    version: 1.0.0
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.915064+07:00"
    description: N/A
    digest: 16d7084c9e3469b3813594d8365cf4c4dc773b2be5436443ebbc07287e1c8339
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9156053+07:00"
    description: N/A
    digest: 4bd1b30ef6c30c34987375762b7876599984d9ba2427c413b426faabbf7962bb
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
  websocket-node-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9161198+07:00"
    description: N/A
    digest: feb7de27f974423655e07b796bcbcb14e3430427d720190652d88eaf1fdb4000
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: websocket-node-build
    urls:
    - packages/websocket-node-build-1.0.0.tgz
    version: 1.0.0
  websocket-node-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-04T00:50:38.9166589+07:00"
    description: N/A
    digest: ae7ef423dbe67501686d9b24d246d44c6a99f3a3f8d4923499306ac2efdfd27a
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: websocket-node-deployment
    urls:
    - packages/websocket-node-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-04T00:50:38.9108727+07:00"
