apiVersion: v1
entries:
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T00:31:16.0106061+07:00"
    description: N/A
    digest: e3a1a6717d83597fc9f0f6c5dc1e13fdd372c29deddef99d46d94ff717f9e4e8
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T00:31:16.0111106+07:00"
    description: N/A
    digest: 7db4f24ab08a6ec983e2ffae5b20904a69675c0d609965184b3ae7749aeac54a
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-11-19T00:31:16.0099602+07:00"
