apiVersion: v1
entries:
  build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-18T21:50:13.7622886+07:00"
    description: N/A
    digest: 478eca6edb04b02f029d9974759b4cfe23181b4970a70360d09d79b611a67ea7
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: build
    urls:
    - packages/build-1.0.0.tgz
    version: 1.0.0
  deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-18T21:50:13.7629302+07:00"
    description: N/A
    digest: 85ae144d2ccf0fd035070dc34d90f043100046baf0a8912330aaca56b9afa224
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: deployment
    urls:
    - packages/deployment-1.0.0.tgz
    version: 1.0.0
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-18T21:50:13.7635521+07:00"
    description: N/A
    digest: 13b781c7d62874c6ce041739cfaa04d25e52196f1ac20dc69a6db10744bd4754
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-18T21:50:13.761111+07:00"
