apiVersion: v1
entries:
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:48:36.2004327+07:00"
    description: N/A
    digest: 6113a4ce5e37207118ff2674857c94d02c5c3ab0fe19853f0925305f3f92ddc5
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:48:36.2004327+07:00"
    description: N/A
    digest: 089aa212c60ab44a3df833f06a79307049c0cfa90cbc120c7e1eb350c766e228
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:48:36.2009536+07:00"
    description: N/A
    digest: 01ad24a55d676d14b576826002bba306088dc2e1309b576afe0296fa370c7a3e
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-11-19T21:48:36.199912+07:00"
