apiVersion: v1
entries:
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:53:33.2052826+07:00"
    description: N/A
    digest: 91afe19792c78cca4c6a587a7b9751f26324d2b7e4fbe10cf6dc9958a7b0a8d3
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:53:33.2052826+07:00"
    description: N/A
    digest: 1788415fb499c1bb91d25b7e909ba0b423f572977c2fdde4d6bcb77879224ae8
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:53:33.2058007+07:00"
    description: N/A
    digest: 9faae510a8b909e9878f7b80ed2e69308585d96cbbbde234ba8f13fd0db4dbc8
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-11-19T21:53:33.2047665+07:00"
