apiVersion: v1
entries:
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T17:54:10.3352017+07:00"
    description: N/A
    digest: 77dcbe08452224fe5aa7ca7d457560f9acee8eda7e5f32cbb28dc88c58c9961e
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T17:54:10.3357513+07:00"
    description: N/A
    digest: 1b3e5e7a3adbbaff436e19483110a823ee917cba551acc6f7e1cb6592265e110
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-11-19T17:54:10.3346613+07:00"
