apiVersion: v1
entries:
  microservice:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2024-12-25T01:19:33.5640429+07:00"
    description: This chart is used to deploy a microservice in a Kubernetes cluster.
    digest: 6958e1eb555245e18ba035eef746c2d4c50c3a57eea593279a73c2ab7534be15
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: microservice
    urls:
    - packages/microservice-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-25T01:19:33.5626706+07:00"
