apiVersion: v1
entries:
  service:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2024-12-26T21:43:22.9067198+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 5061a42d3ce255b085012b2ffacef82e5d0ea4d2360a826c939211a07aef9f9e
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-26T21:43:22.9038135+07:00"
