apiVersion: v1
entries:
  build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-20T15:44:36.2245493+07:00"
    description: N/A
    digest: b5e1710e4b14c53ca7a7e46a39d6b787bc628f55a5d2e2acfd9974a879f50f70
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: build
    urls:
    - packages/build-1.0.0.tgz
    version: 1.0.0
  deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-20T15:44:36.2257291+07:00"
    description: N/A
    digest: 4f39649b8f6fc9ea451f561262e3d0670112c20e7448bc48b3a504e3ce99f55f
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: deployment
    urls:
    - packages/deployment-1.0.0.tgz
    version: 1.0.0
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-20T15:44:36.2263668+07:00"
    description: N/A
    digest: ca9c71fc4ee616fa7262c9598db0b51a158f9329e07c0f34c6c6d0444fd1de79
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-20T15:44:36.2192693+07:00"
