apiVersion: v1
entries:
  service:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2024-12-25T22:31:33.8826763+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 15d330512a7c00fbefca312d64f6ffff3a46a04c558475cde414f044675f70d9
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-25T22:31:33.8767808+07:00"
