apiVersion: v1
entries:
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:44:03.9625748+07:00"
    description: N/A
    digest: 16448bcc10850178a8373281aa784a2b766a91c291292e1655105b748ae35bc2
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-11-19T21:44:03.9625748+07:00"
    description: N/A
    digest: d29976e1310bd45a0981b21ade3d6f2821ab724c1121d98bca44d232fc6ea256
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-11-19T21:44:03.9620493+07:00"
