apiVersion: v1
entries:
  service:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:36.0271976+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 818f08291c4d799dfa213486a88bd57116b2dd27fd0891b84878aa14dd2888d5
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.1.2.tgz
    version: 1.1.2
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:36.0252187+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 7e09773aa80d6c78b9b40f1a24147b1653baebc12f3d3df0ac0b4abbd8468a84
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.1.1.tgz
    version: 1.1.1
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:36.0155502+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 923c64db9b03a5891c22c88ec9dcfdeb4fa13c860ca1839a0714eb4b0f543b58
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.1.0.tgz
    version: 1.1.0
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:36.0047078+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 8c6167055e72641ff56204cf072de2fc58d4812d4b00025b41dee7e6fc60f701
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.9.tgz
    version: 1.0.9
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9954668+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: cbd43d48bb801fb819a97425eb29ba98d0ddce93ee3e6f7435fddf66e3c411b6
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.8.tgz
    version: 1.0.8
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9855555+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: e55d7c5dfb0084a0a5392325d85a49ffc85b93bbacc2441bfd703260162543e0
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.7.tgz
    version: 1.0.7
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9717163+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 28c85a807c22cdff5ca96905322d92e8262e47291a4fad997dac172c04fee555
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.6.tgz
    version: 1.0.6
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9620944+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 29ba9f2f7a20aa1a7c669b653c85db12773bad9a81b02b706c8b657f3e60c1b8
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.5.tgz
    version: 1.0.5
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9448936+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: b6211637d718f0a78bedce4362071fc789da3d42826cd22921329951ee36f3bd
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.4.tgz
    version: 1.0.4
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9323889+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: ad4106901b37d926480e3ed196c0b3957d96e1450ec0528c46c64f22e8ac195f
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.3.tgz
    version: 1.0.3
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9203238+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 771302dea582bfaf64a060a7f754530e421bcdecb1947e68c63e227dd0fabdd6
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.2.tgz
    version: 1.0.2
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.9057919+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 98810a8c67218a93ca75eacf98b7d8aff54d232afecee7207b39402a5b4b37be
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.1.tgz
    version: 1.0.1
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2025-03-03T17:24:35.893242+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 88fcbbe615282c801dbf9080ac562d11125e2d01215373e3f93f4b7d7f54452b
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.0.tgz
    version: 1.0.0
generated: "2025-03-03T17:24:35.8737939+07:00"
