apiVersion: v1
entries:
  cron-worker-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8179795+07:00"
    description: N/A
    digest: f2a5cb5425fca2cc3b78e06f34b767549b6bfa9a96b5e6d896da41c6414a19a4
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-worker-build
    urls:
    - packages/cron-worker-build-1.0.0.tgz
    version: 1.0.0
  cron-worker-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8179795+07:00"
    description: N/A
    digest: 38892afaba2b9a969eee115c9c53433c38e5b6b2f7aa67cd39f494cfba5f93d6
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-worker-deployment
    urls:
    - packages/cron-worker-deployment-1.0.0.tgz
    version: 1.0.0
  gameplay-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.818525+07:00"
    description: N/A
    digest: a5c316f8a98690b3d0fe6a5aad8aeed790d833a47d3a90f556119333bcc966d6
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: gameplay-service-build
    urls:
    - packages/gameplay-service-build-1.0.0.tgz
    version: 1.0.0
  gameplay-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.818525+07:00"
    description: N/A
    digest: a16546e4e8648c1697350dc741f5f6a07c99587add31c15c30d4035101666905
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: gameplay-service-deployment
    urls:
    - packages/gameplay-service-deployment-1.0.0.tgz
    version: 1.0.0
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8206363+07:00"
    description: N/A
    digest: d72c6398b51b716067d650cb374b813f55d815000615386acabcfef17c262c0d
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
  rest-api-gateway-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8206363+07:00"
    description: N/A
    digest: 8446d0131b052bd123aa19f02906dfc2efec87de827b9e5b2b878e58b8c234da
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: rest-api-gateway-build
    urls:
    - packages/rest-api-gateway-build-1.0.0.tgz
    version: 1.0.0
  rest-api-gateway-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.821183+07:00"
    description: N/A
    digest: 09004bdbae9ace54cbe5c23cbc005b3dee341c1ef51903059c475fd3f5416285
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: rest-api-gateway-deployment
    urls:
    - packages/rest-api-gateway-deployment-1.0.0.tgz
    version: 1.0.0
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.821183+07:00"
    description: N/A
    digest: dd47b11013f431309920072e8e827a8f2a7c8b3300077796462f038d1a822340
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8217337+07:00"
    description: N/A
    digest: 85da94ae983fd344975c535aead2358a4885a29cb83c74aec31c7a8020dc1f19
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
  websocket-node-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8223507+07:00"
    description: N/A
    digest: 13a88e76e99e83e50523812d55c0acec1acc42cf211ab6ea163d2d2a16ab6a23
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: websocket-node-build
    urls:
    - packages/websocket-node-build-1.0.0.tgz
    version: 1.0.0
  websocket-node-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T17:19:40.8223507+07:00"
    description: N/A
    digest: dbfde85936b75015ef724018a717c341a8b47f165c647ecf5473b0105931541d
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: websocket-node-deployment
    urls:
    - packages/websocket-node-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-02T17:19:40.8174387+07:00"
