apiVersion: v1
entries:
  cron-scheduler-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2035069+07:00"
    description: N/A
    digest: b9ece4e877df61cfa87ebe562bbdf579eefdf783519c45737c6521d81d119848
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-scheduler-build
    urls:
    - packages/cron-scheduler-build-1.0.0.tgz
    version: 1.0.0
  cron-scheduler-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2035069+07:00"
    description: N/A
    digest: c653d0dc46c42c63b65e1833442efce704bfb205540231f07370c5f5bb4f09d7
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-scheduler-deployment
    urls:
    - packages/cron-scheduler-deployment-1.0.0.tgz
    version: 1.0.0
  cron-worker-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2035069+07:00"
    description: N/A
    digest: 8a472b4b1944328137319c7d12e96bf507b9339ddf03eda75dba60e1bccb8b33
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-worker-build
    urls:
    - packages/cron-worker-build-1.0.0.tgz
    version: 1.0.0
  cron-worker-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2035069+07:00"
    description: N/A
    digest: b194e30c4e2f0349959fc72702a1be1bb196437a432dd6cb6cdc2ae573570b60
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: cron-worker-deployment
    urls:
    - packages/cron-worker-deployment-1.0.0.tgz
    version: 1.0.0
  gameplay-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2078697+07:00"
    description: N/A
    digest: f1707125e1b8b3ed7d65ac3e6006b7d7c6b20167071b97adb378e2999107ef3b
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: gameplay-service-build
    urls:
    - packages/gameplay-service-build-1.0.0.tgz
    version: 1.0.0
  gameplay-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2078697+07:00"
    description: N/A
    digest: c93663f71eb51cbed37c20f72d6252f4cda9bd677a25f7de7abe92f72702e45d
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: gameplay-service-deployment
    urls:
    - packages/gameplay-service-deployment-1.0.0.tgz
    version: 1.0.0
  ingress:
  - annotations:
      category: Ingress
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2078697+07:00"
    description: N/A
    digest: 2644ef9903655b8c1894dfd04534c34d3fae861995adb2e832bbaf4cbcc5f3b1
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: ingress
    urls:
    - packages/ingress-1.0.0.tgz
    version: 1.0.0
  rest-api-gateway-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2078697+07:00"
    description: N/A
    digest: c0870bb053f83aa30c84318d8a0058603436c4f9f277e0bb7a1aa683880a48e7
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: rest-api-gateway-build
    urls:
    - packages/rest-api-gateway-build-1.0.0.tgz
    version: 1.0.0
  rest-api-gateway-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2097739+07:00"
    description: N/A
    digest: 15915d1fbfc30f63a718a4685db2552e0047de442f7c821cf48c3afd017b5dc0
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: rest-api-gateway-deployment
    urls:
    - packages/rest-api-gateway-deployment-1.0.0.tgz
    version: 1.0.0
  wallet-service-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2104371+07:00"
    description: N/A
    digest: 089aa212c60ab44a3df833f06a79307049c0cfa90cbc120c7e1eb350c766e228
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-build
    urls:
    - packages/wallet-service-build-1.0.0.tgz
    version: 1.0.0
  wallet-service-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2104371+07:00"
    description: N/A
    digest: 01ad24a55d676d14b576826002bba306088dc2e1309b576afe0296fa370c7a3e
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: wallet-service-deployment
    urls:
    - packages/wallet-service-deployment-1.0.0.tgz
    version: 1.0.0
  websocket-node-build:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2104371+07:00"
    description: N/A
    digest: 9102e5fb946002c1ee2a99cddc99e9676a723e9c2e7209c1d097c0ee9fb2429c
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: websocket-node-build
    urls:
    - packages/websocket-node-build-1.0.0.tgz
    version: 1.0.0
  websocket-node-deployment:
  - annotations:
      category: Deployment
      licenses: MIT
    apiVersion: v1
    appVersion: 1.1.0
    created: "2024-12-02T16:49:45.2104371+07:00"
    description: N/A
    digest: c052397165e91dca1f119de38b8f8cd0907b41d28fe05e29e436cfb5ad87797c
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: websocket-node-deployment
    urls:
    - packages/websocket-node-deployment-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-02T16:49:45.2035069+07:00"
