apiVersion: v1
entries:
  service:
  - annotations:
      category: Service
      licenses: MIT
    apiVersion: v1
    appVersion: 1.0.0
    created: "2024-12-25T19:19:08.0869991+07:00"
    description: This chart is used to deploy any CiFarm service in a Kubernetes cluster.
    digest: 71923ba5787fdade5405a5a4c114708b827f782176a327dea7c80beb3ec7eba4
    home: N/A
    icon: N/A
    keywords:
    - service
    maintainers:
    - name: CiLab 2.0
    name: service
    urls:
    - packages/service-1.0.0.tgz
    version: 1.0.0
generated: "2024-12-25T19:19:08.0845021+07:00"
