---
# Source: wallet-service/templates/cluster-ip.yaml
apiVersion: v1
kind: Service
metadata:
  name: wallet-service 
  labels:
    mode: deploy
spec:
  selector:
    app.kubernetes.io/name: wallet-service
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
  type: ClusterIP
---
# Source: wallet-service/templates/kaniko-build.yaml
apiVersion: v1
kind: Pod
metadata:
  name: wallet-service-kaniko-build
  labels: 
    mode: build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
      - "--context=git://github.com/starci-lab/cifarm-containers"
      - "--destination=starci183/wallet-service:latest"
      - "--dockerfile=./apps/wallet-service/Dockerfile"
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
---
# Source: wallet-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service-deployment
  labels:
    mode: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: starci183/wallet-service:latest
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: wallet-service-env
          ports:
            - containerPort: 3008
