debug: true
replicaCount: 3
containerPort: 3008

metadata:
  clusterName: "wallet-service"
  namespace: "wallet-service"

build:
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
  image:
    repository: starci183/wallet-service
    tag: latest