debug: true
# Global values
metadata:
  clusterName: "wallet-service"        # Tên Service
  namespace: "wallet-service"         # Namespace của Service

buildNamespace: build                 # Namespace cho Kaniko build

# Build configuration
build:
  image:
    repository: cifarm/wallet-service
    tag: latest
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
  dockerfile: ./apps/wallet-service/Dockerfile
  context: git://github.com/starci-lab/cifarm-containers

# Deployment configuration
deployment:
  replicaCount: 3                        # Số lượng replicas
  containerPort: 3008                    # Cổng container
  resources:
    limits:
      cpu: "250m"
      memory: "256Mi"

  envSecret: wallet-service-env          # Secret chứa các biến môi trường
