apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    mode: deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: auth-service-env
          ports:
            - containerPort:  {{ .Values.containerPort }}

#kubectl exec -it auth-service-deployment-67448d654f-8jrwf -- netstat -tuln