apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip
  labels:
    mode: deploy
spec:
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP