apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cifarm-redis-master-persistent-volume-claim
  namespace: default
spec:
  storageClassName: cifarm-redis-master-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi