apiVersion: v1
kind: Pod
metadata:
  name: redis-cluster
  labels:
    app: cifarm
spec:
  initContainers:
    # master
    - name: redis-master
      restartPolicy: Always
      image: bitnami/redis:latest
      env:
        - name: REDIS_REPLICATION_MODE
          value: "master"

        # REDIS_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      ports:
        - containerPort: 6379
      volumeMounts:
      - name: volume
        mountPath: /var/lib/volume
  
  containers:
    - name: redis-slave
      image: bitnami/redis:latest
      env:
        # REDIS_REPLICATION_MODE
        - name: REDIS_REPLICATION_MODE
          value: "slave"
        
        # REDIS_MASTER_HOST
        - name: REDIS_MASTER_HOST
          value: "127.0.0.1"

        # REDIS_MASTER_PORT_NUMBER
        - name: REDIS_MASTER_PORT_NUMBER
          value: "6379"

        # REDIS_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"

        # REDIS_PORT_NUMBER
        - name: REDIS_PORT_NUMBER
          value: "6380"
      ports:
        - containerPort: 6380
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: cifarm-redis-master-persistent-volume-claim