# Redis Cache Configuration (non-sensitive, can go to ConfigMap)
envVarsCM:
  CACHE_REDIS_HOST: "${cache_redis_host}"
  CACHE_REDIS_PORT: "${cache_redis_port}" # Ensure the port is a string
  CACHE_REDIS_CLUSTER_ENABLED: "${cache_redis_cluster_enabled}" # Ensure the value is a string

  JOB_REDIS_HOST: "${job_redis_host}"
  JOB_REDIS_PORT: "${job_redis_port}" # Ensure the port is a string
  JOB_REDIS_CLUSTER_ENABLED: "${job_redis_cluster_enabled}" # Ensure the value is a string
 
  # Gameplay Test Postgres Configuration (non-sensitive, can go to ConfigMap)
  GAMEPLAY_MONGODB_DBNAME: "${gameplay_mongodb_database}"
  GAMEPLAY_MONGODB_HOST: "${gameplay_mongodb_host}"
  GAMEPLAY_MONGODB_PORT: "${gameplay_mongodb_port}"
  
  CRON_SCHEDULER_HEALTH_CHECK_PORT: "${health_check_port}"  # Specify as string to avoid YAML parsing errors

  # Kafka Configuration (non-sensitive, can go to ConfigMap)
  KAFKA_HOST: "${kafka_host}"
  KAFKA_PORT: "${kafka_port}"
  KAFKA_SASL_ENABLED: "${kafka_sasl_enabled}"

envVarsSecret:
  # Redis Cache Configuration (sensitive, should go to Secrets)
  CACHE_REDIS_PASSWORD: "${cache_redis_password}" # Ensure the password is a string

  # Job Redis Cache Configuration (sensitive, should go to Secrets)
  JOB_REDIS_PASSWORD: "${job_redis_password}" # Ensure the password is a string

  # Gameplay Test Postgres Configuration (sensitive, should go to Secrets)
  GAMEPLAY_MONGODB_USERNAME: "${gameplay_mongodb_username}"
  GAMEPLAY_MONGODB_PASSWORD: "${gameplay_mongodb_password}"

  # Kafka SASL Configuration (sensitive, should go to Secrets)
  KAFKA_SASL_USERNAME: "${kafka_sasl_username}"
  KAFKA_SASL_PASSWORD: "${kafka_sasl_password}"

  # Cipher Secret (sensitive, should go to Secrets)
  CIPHER_SECRET: "${cipher_secret}"

containerPorts:
  app:
    enabled: false
  healthCheck:
    port: ${health_check_port}  # Health check port exposed by the container.

service:
  ports:
    app:
      enabled: false
    healthCheck:
      port: ${health_check_port}  # Health check port exposed by the service.

image:
  registry: docker.io  # Docker registry URL for the image.
  repository: cifarm/cron-scheduler  # Repository for the container image.
  tag: latest  # Tag for the image.
  digest: ""  # Optionally specify an image digest.
  pullPolicy: Always  # Image pull policy, can be 'Always', 'IfNotPresent', or 'Never'.
  pullSecrets: []  # Secrets for private image pull.

nodeSelector:
  "doks.digitalocean.com/node-pool": ${node_pool_label}

resources:
  requests:
    cpu: ${request_cpu}
    memory: ${request_memory}
  limits:
    cpu: ${limit_cpu}
    memory: ${limit_memory}

# RBAC and Service Account Configuration
rbac:
  create: true  # Enable creation of RBAC resources.
  rules:
    - apiGroups: ["coordination.k8s.io"]
      resources: ["leases"]
      verbs: ["get", "watch", "list", "create", "update", "delete"]

serviceAccount:
  create: true  # Enable creation of a service account.
  name: ""  # Optionally specify a service account name.
  annotations: {}  # Add annotations for the service account if needed.
  automountServiceAccountToken: true  # Automount the service account token.