replicaCount: 1
# Redis Cache Configuration (non-sensitive, can go to ConfigMap)
envVarsCM:
  CACHE_REDIS_HOST: "${cache_redis_host}"
  CACHE_REDIS_PORT: "${cache_redis_port}" # Ensure the port is a string
  CACHE_REDIS_CLUSTER_ENABLED: "${cache_redis_cluster_enabled}" # Ensure the value is a string
  CACHE_REDIS_CLUSTER_RUN_IN_DOCKER: "false" # Ensure the value is a string

  # Gameplay Test Postgres Configuration (non-sensitive, can go to ConfigMap)
  GAMEPLAY_MONGODB_DBNAME: "${gameplay_mongodb_database}"
  GAMEPLAY_MONGODB_HOST: "${gameplay_mongodb_host}"
  GAMEPLAY_MONGODB_PORT: "${gameplay_mongodb_port}"
  
  GAMEPLAY_SUBGRAPH_PORT: "${port}"  # Specify as string to avoid YAML parsing errors
  GAMEPLAY_SUBGRAPH_HEALTH_CHECK_PORT: "${health_check_port}"  # Specify as string to avoid YAML parsing errors

  # Kafka Configuration (non-sensitive, can go to ConfigMap)
  KAFKA_HOST: "${kafka_host}"
  KAFKA_PORT: "${kafka_port}"
  KAFKA_SASL_ENABLED: "${kafka_sasl_enabled}"

envVarsSecret:
  JWT_SECRET: "${jwt_secret}"

  # Redis Cache Configuration (sensitive, should go to Secrets)
  CACHE_REDIS_PASSWORD: "${cache_redis_password}" # Ensure the password is a string

  # Gameplay Test Postgres Configuration (sensitive, should go to Secrets)
  GAMEPLAY_MONGODB_USERNAME: "${gameplay_mongodb_username}"
  GAMEPLAY_MONGODB_PASSWORD: "${gameplay_mongodb_password}"

   # Kafka SASL Configuration (sensitive, should go to Secrets)
  KAFKA_SASL_USERNAME: "${kafka_sasl_username}"
  KAFKA_SASL_PASSWORD: "${kafka_sasl_password}"

  # Honeycomb Configuration (sensitive, should go to Secrets)
  SOLANA_HONEYCOMB_AUTHORITY_PRIVATE_KEY_MAINNET: "${solana_honeycomb_authority_private_key_mainnet}"
  SOLANA_HONEYCOMB_AUTHORITY_PRIVATE_KEY_TESTNET: "${solana_honeycomb_authority_private_key_testnet}"

  # Metaplex Configuration (sensitive, should go to Secrets)
  SOLANA_METAPLEX_AUTHORITY_PRIVATE_KEY_MAINNET: "${solana_metaplex_authority_private_key_mainnet}"
  SOLANA_METAPLEX_AUTHORITY_PRIVATE_KEY_TESTNET: "${solana_metaplex_authority_private_key_testnet}"

  # Solana Vault Configuration (sensitive, should go to Secrets)
  SOLANA_VAULT_PRIVATE_KEY_TESTNET: "${solana_vault_private_key_testnet}"
  SOLANA_VAULT_PRIVATE_KEY_MAINNET: "${solana_vault_private_key_mainnet}"

  # DigitalOcean Spaces Configuration (sensitive, should go to Secrets)
  S3_DIGITALOCEAN1_ENDPOINT: "${s3_digitalocean1_endpoint}"
  S3_DIGITALOCEAN1_ACCESS_KEY_ID: "${s3_digitalocean1_access_key_id}"
  S3_DIGITALOCEAN1_SECRET_ACCESS_KEY: "${s3_digitalocean1_secret_access_key}"
  S3_DIGITALOCEAN1_REGION: "${s3_digitalocean1_region}"
  S3_DIGITALOCEAN1_BUCKET_NAME: "${s3_digitalocean1_bucket_name}"

  # Cipher Secret (sensitive, should go to Secrets)
  CIPHER_SECRET: "${cipher_secret}"

containerPorts:
  app:
    port: ${port}  # Port exposed by the container.
  healthCheck:
    port: ${health_check_port}  # Health check port exposed by the container.

service:
  ports:
    app:
      port: ${port}  # Port exposed by the service.
    healthCheck:
      port: ${health_check_port}  # Health check port exposed by the service.

image:
  registry: docker.io  # Docker registry URL for the image.
  repository: cifarm/gameplay-subgraph  # Repository for the container image.
  tag: latest  # Tag for the image.
  digest: ""  # Optionally specify an image digest.
  pullPolicy: Always  # Image pull policy, can be 'Always', 'IfNotPresent', or 'Never'.
  pullSecrets: []  # Secrets for private image pull.

nodeSelector:
  "doks.digitalocean.com/node-pool": ${node_pool_label}

resources:
  requests:
    cpu: ${request_cpu}
    memory: ${request_memory}
  limits:
    cpu: ${limit_cpu}
    memory: ${limit_memory}