apiVersion: v1
kind: Pod
metadata:
  name: build-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["/busybox/sleep", "infinity"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    resources:
      requests:
        cpu: ${requests_cpu}  # Request 100 milliCPU
        memory: ${requests_memory}  # Request 128Mi of memory
      limits:
        cpu: ${limits_cpu}  # Limit to 200 milliCPU
        memory: ${limits_memory}  # Limit to 256Mi of memory
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: ${secret_name}
        items:
          - key: .dockerconfigjson
            path: config.json