
crds: 
 install: true

rbac: 
 create: true
 enabledCustomScaledRefKinds: false

nodeSelector:
   "doks.digitalocean.com/node-pool": ${node_group_label}

prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: ${interval_scrape}
      scrapeTimeout:  ${timeout_scrape}
      additionalLabels:
        release: ${service_monitor_selector}  

  operator:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: ${interval_scrape}
      scrapeTimeout:  ${timeout_scrape}
      additionalLabels:
        release: ${service_monitor_selector}    

  webhooks:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: ${interval_scrape}
      scrapeTimeout:  ${timeout_scrape}
      additionalLabels:
        release: ${service_monitor_selector}   

resources:
  operator:
    requests:
      cpu: ${operator_request_cpu}
      memory: ${operator_request_memory}
    limits:
      cpu: ${operator_limit_cpu}
      memory: ${operator_limit_memory}

  metricServer:
    requests:
      cpu: ${metric_server_request_cpu}
      memory: ${metric_server_request_memory}
    limits:
      cpu: ${metric_server_limit_cpu}
      memory: ${metric_server_limit_memory}

  webhooks:
    requests:
      cpu: ${webhooks_request_cpu}
      memory: ${webhooks_request_memory}
    limits:
      cpu: ${webhooks_limit_cpu}
      memory: "${webhooks_limit_memory}"