# Resources for the cainjector component
cainjector:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: 30m
      memory: 60Mi
    limits:
      cpu: 90m
      memory: 180Mi

# Resources for the controller component
controller:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: 30m
      memory: 60Mi
    limits:
      cpu: 90m
      memory: 180Mi

# Resources for the webhook component
webhook:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: 30m
      memory: 60Mi
    limits:
      cpu: 90m
      memory: 180Mi