rbac:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: ${cluster_autoscaler_iam_role_arn}
    name: cluster-autoscaler
autoDiscovery:
  clusterName: ${cluster_name}

awsRegion: ${region}

nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
resources:
  requests:
    cpu: 30m
    memory: 60Mi
  limits:
    cpu: 90m
    memory: 180Mi
extraArgs:
  balance-similar-node-groups: true
  skip-nodes-with-system-pods: false
  skip-nodes-with-local-storage: false
  expander: least-waste
  scale-down-enabled: true