# Redis Cache Configuration (non-sensitive, can go to ConfigMap)
envVarsCM:
  CACHE_REDIS_HOST: "${cache_redis_host}"
  CACHE_REDIS_PORT: "${cache_redis_port}" # Ensure the port is a string
  CACHE_REDIS_CLUSTER_ENABLED: "${cache_redis_cluster_enabled}" # Ensure the value is a string
  CACHE_REDIS_CLUSTER_RUN_IN_DOCKER: "false" # Ensure the value is a string

  # Gameplay Postgres Configuration (non-sensitive, can go to ConfigMap)
  GAMEPLAY_POSTGRESQL_DBNAME: "${gameplay_postgresql_database}"
  GAMEPLAY_POSTGRESQL_HOST: "${gameplay_postgresql_host}"
  GAMEPLAY_POSTGRESQL_PORT: "${gameplay_postgresql_port}"
  
  # Gameplay Service Configuration (non-sensitive, can go to ConfigMap)
  GAMEPLAY_SERVICE_PORT: "${port}"  # Specify as string to avoid YAML parsing errors
  GAMEPLAY_SERVICE_HEALTH_CHECK_PORT: "${health_check_port}"  # Specify as string to avoid YAML parsing errors
  
# Kafka Configuration (non-sensitive, can go to ConfigMap)
  KAFKA_HOST: "${kafka_host}"
  KAFKA_PORT: "${kafka_port}"
  KAFKA_SASL_ENABLED: "${kafka_sasl_enabled}"

# JWT Authentication Configuration (sensitive, should go to Secrets)
envVarsSecret:
  JWT_SECRET: "${jwt_secret}"
  JWT_ACCESS_TOKEN_EXPIRATION: "${jwt_access_token_expiration}"
  JWT_REFRESH_TOKEN_EXPIRATION: "${jwt_refresh_token_expiration}"
  
  # Kafka SASL Configuration (sensitive, should go to Secrets)
  KAFKA_SASL_USERNAME: "${kafka_sasl_username}"
  KAFKA_SASL_PASSWORD: "${kafka_sasl_password}"

  # Gameplay Postgres Configuration (sensitive, should go to Secrets)
  GAMEPLAY_POSTGRESQL_USERNAME: "${gameplay_postgresql_username}"
  GAMEPLAY_POSTGRESQL_PASSWORD: "${gameplay_postgresql_password}"

  # Redis Cache Configuration (sensitive, should go to Secrets)
  CACHE_REDIS_PASSWORD: "${cache_redis_password}"

containerPorts:
  app:
    port: ${port}  # Port exposed by the container.
  healthCheck:
    port: ${health_check_port}  # Health check port exposed by the container.

service:
  ports:
    app:
      port: ${port}  # Port exposed by the service.
    healthCheck:
      port: ${health_check_port}  # Health check port exposed by the service.

image:
  registry: docker.io  # Docker registry URL for the image.
  repository: cifarm/gameplay-service  # Repository for the container image.
  tag: latest  # Tag for the image.
  digest: ""  # Optionally specify an image digest.
  pullPolicy: Always  # Image pull policy, can be 'Always', 'IfNotPresent', or 'Never'.
  pullSecrets: []  # Secrets for private image pull.

nodeSelector:
  "eks.amazonaws.com/nodegroup": ${node_group_label}

resources:
  requests:
    cpu: ${request_cpu}
    memory: ${request_memory}
  limits:
    cpu: ${limit_cpu}
    memory: ${limit_memory}