# Redis Cache Configuration (non-sensitive, can go to ConfigMap)
envVarsCM:
  CACHE_REDIS_HOST: "${cache_redis_host}"
  CACHE_REDIS_PORT: "${cache_redis_port}" # Ensure the port is a string

  # Gameplay Test Postgres Configuration (non-sensitive, can go to ConfigMap)
  GAMEPLAY_POSTGRESQL_DBNAME: "${gameplay_postgresql_database}"
  GAMEPLAY_POSTGRESQL_HOST: "${gameplay_postgresql_host}"
  GAMEPLAY_POSTGRESQL_PORT: "${gameplay_postgresql_port}"
  GAMEPLAY_POSTGRESQL_USERNAME: "${gameplay_postgresql_username}"
  GAMEPLAY_POSTGRESQL_PASSWORD: "${gameplay_postgresql_password}"
  
  GAMEPLAY_SUBGRAPH_PORT: "${port}"  # Specify as string to avoid YAML parsing errors
  GAMEPLAY_SUBGRAPH_HEALTH_CHECK_PORT: "${health_check_port}"  # Specify as string to avoid YAML parsing errors

containerPorts:
  - name: app
    containerPort: ${port}  # App port exposed by the container.
    protocol: TCP
  - name: health-check
    containerPort: ${health_check_port}  # Health check port exposed by the container.
    protocol: TCP

service:
  ports:
  - name: app
    port: ${port}  # Port exposed by the service.
    targetPort: app  # Port exposed by the container.
    protocol: TCP  # Protocol used by the service.
  - name: health-check
    port: ${health_check_port}  # Health check port exposed by the service.
    targetPort: health-check  # Health check port exposed by the container.
    protocol: TCP  # Protocol used by the service.

image:
  registry: docker.io  # Docker registry URL for the image.
  repository: cifarm/gameplay-subgraph  # Repository for the container image.
  tag: latest  # Tag for the image.
  digest: ""  # Optionally specify an image digest.
  pullPolicy: Always  # Image pull policy, can be 'Always', 'IfNotPresent', or 'Never'.
  pullSecrets: []  # Secrets for private image pull.

nodeSelector:
  "eks.amazonaws.com/nodegroup": ${node_group_label}

resources:
  requests:
    cpu: ${request_cpu}
    memory: ${request_memory}
  limits:
    cpu: ${limit_cpu}
    memory: ${limit_memory}