# grafana-values.yaml

# Admin credentials for the Grafana instance
admin:
  user: ${user}  # Set admin username
  password: ${password}  # Set admin password

# Enable or disable metrics collection
metrics:
  enabled: true  # Set to true to enable metrics

# Resource requests and limits for the Grafana pod
grafana:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: "30m"  # Minimum CPU requested for the Grafana pod
      memory: "60Mi"  # Minimum memory requested for the Grafana pod
    limits:
      cpu: "90m"  # Maximum CPU limit for the Grafana pod
      memory: "180Mi"  # Maximum memory limit for the Grafana pod

# Data sources configuration for Grafana
datasources:
  secretDefinition:
    apiVersion: 1  # API version for the datasource configuration
    datasources:
      # Configuration for the Prometheus data source
      - name: Prometheus
        type: prometheus  # Type of the data source
        access: proxy  # Access mode (proxy means the Grafana pod will access the data source directly)
        orgId: 1  # Organization ID in Grafana (default organization)
        url: ${prometheus_url}  # URL for Prometheus instance
        version: 1  # Version of the data source configuration
        editable: true  # Allow users to edit the data source configuration
        isDefault: true  # Set this as the default data source
        basicAuth: true
        basicAuthUser: example
        secureJsonData:
          basicAuthPassword: example
        jsonData:
          httpMethod: POST        # HTTP method (POST or GET)
          keepCookies: []         # Cookies to keep
          timeInterval: "5s"     # Time interval between queries
          queryTimeout: "30s"    # Timeout for each query
          tlsSkipVerify: false    # Skip TLS certificate verification (if any)

      # Configuration for the Alertmanager data source
      - name: Alertmanager
        uid: alertmanager  # Unique identifier for Alertmanager
        type: alertmanager  # Type of the data source
        access: proxy  # Access mode (proxy means the Grafana pod will access the data source directly)
        orgId: 1  # Organization ID in Grafana
        url: ${prometheus_alertmanager_url}  # URL for Alertmanager instance
        version: 1  # Version of the data source configuration
        editable: true  # Allow users to edit the data source configuration
        basicAuth: true
        basicAuthUser: example
        secureJsonData:
          basicAuthPassword: example
        jsonData:
          implementation: prometheus  # Implementation type (Prometheus)
          httpMethod: POST        # HTTP method (POST or GET)
          keepCookies: []         # Cookies to keep
          timeInterval: "5s"     # Time interval between queries
          queryTimeout: "30s"     # Timeout for each query
          tlsSkipVerify: false    # Skip TLS certificate verification (if any)
