replicaCount: 2
# Jenkins configuration
jenkinsUser: ${user}
jenkinsPassword: ${password}

# Resource requests and limits
resources:
  requests:
    cpu: "120m"
    memory: "240Mi"
  limits:
    cpu: "360m"
    memory: "720Mi"

# Service configuration
service:
  type: ClusterIP

plugins: [
  "aws-credentials",
  "kubernetes",
]
