replicaCount: 1
# Jenkins configuration
jenkinsUser: ${user}
jenkinsPassword: ${password}

# Resource requests and limits
resources:
  requests:
    cpu: "240m"
    memory: "480Mi"
  limits:
    cpu: "720m"
    memory: "1440Mi"

# Service configuration
service:
  type: ClusterIP

plugins: [
  "aws-credentials",
  "kubernetes",
]
