# kafka-values.yaml

# Kafka listeners configuration
listeners:
  client:
    protocol: "PLAINTEXT"  # Protocol for client communication
  controller:
    protocol: "PLAINTEXT"  # Protocol for controller communication
# Kafka controller resource requests and limits
controller:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: "120m"          # Minimum CPU requested for the controller (20 millicores)
      memory: "240Mi"      # Minimum memory requested for the controller (40 MiB)
    limits:
      cpu: "360m"         # Maximum CPU allowed for the controller (200 millicores)
      memory: "720Mi"     # Maximum memory allowed for the controller (400 MiB)

# Kafka broker configuration
# broker:
#   nodeSelector:
#     "eks.amazonaws.com/nodegroup": ${node_group_label}
  # resources:
  #   requests:
  #     cpu: "10m"          # Minimum CPU requested for the broker (20 millicores)
  #     memory: "20Mi"      # Minimum memory requested for the broker (40 MiB)
  #   limits:
  #     cpu: "90m"         # Maximum CPU allowed for the broker (200 millicores)
  #     memory: "180Mi"     # Maximum memory allowed for the broker (400 MiB)

# # Kafka provisioning resource requests and limits
# provisioning:
#   nodeSelector:
#     "eks.amazonaws.com/nodegroup": ${node_group_label}
#   resources:
#     requests:
#       cpu: "10m"          # Minimum CPU requested for the provisioning (20 millicores)
#       memory: "20Mi"      # Minimum memory requested for the provisioning (40 MiB)
#     limits:
#       cpu: "90m"         # Maximum CPU allowed for the provisioning (200 millicores)
#       memory: "180Mi"     # Maximum memory allowed for the provisioning (400 MiB)