# Global PostgreSQL settings
global:
  postgresql:
    # The name of the PostgreSQL database to be created
    database: ${database}          # Replace example with your database name
    
    # The password for the PostgreSQL superuser
    password: ${password}          # Replace example with your password
    
    # The name of the repmgr database used for replication
    repmgrDatabase: ${database}    # Replication database name (usually same as database)
    
    # The password for the PostgreSQL replication user
    repmgrPassword: ${password}    # Password for the repmgr user

# PostgreSQL PGPool resource configurations (for connection pooling)
pgpool:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    # Resource requests for PGPool, setting the CPU and memory needed at a minimum
    requests:
      cpu: "60m"                       # Set the requested CPU for PGPool (40 millicores)
      memory: "120Mi"                   # Set the requested memory for PGPool (80 MiB)
    
    # Resource limits for PGPool, setting the maximum CPU and memory PGPool can use
    limits:
      cpu: "180m"                      # Set the maximum CPU for PGPool (400 millicores)
      memory: "360Mi"                  # Set the maximum memory for PGPool (800 MiB)

# PostgreSQL database resource configurations (for the main PostgreSQL instances)
postgresql:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    # Resource requests for PostgreSQL, setting the CPU and memory needed at a minimum
    requests:
      cpu: "30m"                       # Set the requested CPU for PostgreSQL (20 millicores)
      memory: "60Mi"                   # Set the requested memory for PostgreSQL (40 MiB)
    
    # Resource limits for PostgreSQL, setting the maximum CPU and memory PostgreSQL can use
    limits:
      cpu: "90m"                      # Set the maximum CPU for PostgreSQL (200 millicores)
      memory: "180Mi"                  # Set the maximum memory for PostgreSQL (400 MiB)

# Witness server resource configurations (for the HA witness pod)
witness:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    # Resource requests for the witness pod, setting the CPU and memory needed at a minimum
    requests:
      cpu: "30m"                       # Set the requested CPU for witness (10 millicores)
      memory: "60Mi"                   # Set the requested memory for witness (20 MiB)
    
    # Resource limits for the witness pod, setting the maximum CPU and memory it can use
    limits:
      cpu: "90m"                      # Set the maximum CPU for witness (100 millicores)
      memory: "180Mi"                  # Set the maximum memory for witness (200 MiB)