# redis-values.yaml

# Disable authentication for Redis
auth:
  enabled: false

# Redis replica configuration
replica:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"               # CPU request for Redis replica (10 millicores)
      memory: "100Mi"           # Memory request for Redis replica (20 MiB)
    limits:
      cpu: "100m"              # CPU limit for Redis replica (100 millicores)
      memory: "200Mi"          # Memory limit for Redis replica (200 MiB)

# Redis master configuration
master:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: "100m"               # CPU request for Redis master (20 millicores)
      memory: "200Mi"           # Memory request for Redis master (40 MiB)
    limits:
      cpu: "200m"              # CPU limit for Redis master (200 millicores)
      memory: "400Mi"          # Memory limit for Redis master (400 MiB)