# redis-values.yaml

# Disable authentication for Redis
auth:
  enabled: false

# Redis replica configuration
replica:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  replicaCount: 1
  resources:
    requests:
      cpu: "30m"               # CPU request for Redis replica (10 millicores)
      memory: "60Mi"           # Memory request for Redis replica (20 MiB)
    limits:
      cpu: "90m"              # CPU limit for Redis replica (100 millicores)
      memory: "180Mi"          # Memory limit for Redis replica (200 MiB)

# Redis master configuration
master:
  nodeSelector:
    "eks.amazonaws.com/nodegroup": ${node_group_label}
  resources:
    requests:
      cpu: "60m"               # CPU request for Redis master (20 millicores)
      memory: "120Mi"           # Memory request for Redis master (40 MiB)
    limits:
      cpu: "180m"              # CPU limit for Redis master (200 millicores)
      memory: "360Mi"          # Memory limit for Redis master (400 MiB)