# Redis Cache Configuration (non-sensitive, can go to ConfigMap)
envVarsCM:
  GAMEPLAY_SERVICE_HOST: "${gameplay_service_host}"
  GAMEPLAY_SERVICE_PORT: "${gameplay_service_port}"
  # Rest Api Gateway configuration
  REST_API_GATEWAY_PORT: "${port}"

# JWT Authentication Configuration (sensitive, should go to Secrets)
envVarsSecret:
  JWT_SECRET: "${jwt_secret}"

containerPorts:
  app: ${port}  # App port exposed by the container.

image:
  registry: docker.io  # Docker registry URL for the image.
  repository: cifarm/rest-api-gateway  # Repository for the container image.
  tag: latest  # Tag for the image.
  digest: ""  # Optionally specify an image digest.
  pullPolicy: Always  # Image pull policy, can be 'Always', 'IfNotPresent', or 'Never'.
  pullSecrets: []  # Secrets for private image pull.

nodeSelector:
  "eks.amazonaws.com/nodegroup": ${node_group_label}

resources:
  requests:
    cpu: ${request_cpu}
    memory: ${request_memory}
  limits:
    cpu: ${limit_cpu}
    memory: ${limit_memory}