# Image configuration
image:
  repository: "cifarm/rest-api-gateway"
  tag: "latest"

# Service-related configuration
service: 
  type: "ClusterIP"
  port: ${port}
  targetPort: ${port}

env:
  GAMEPLAY_SERVICE_HOST: ${gameplay_service_host}
  GAMEPLAY_SERVICE_PORT: ${gameplay_service_port}
  # Rest Api Gateway configuration
  REST_API_GATEWAY_PORT: ${port}

# Resources configuration
resources:
  requests:
    cpu: "60m"
    memory: "120Mi"
  limits:
    cpu: "180m"
    memory: "360Mi"

# Node selector configuration
nodeSelector: 
  "eks.amazonaws.com/nodegroup": ${node_group_label}

# Prometheus configuration
prometheus:
  serverAddress:
    host:
      name: "prometheus-kube-prometheus-prometheus"
      namespace: "monitoring"
    port: 9090
  metricName: "rest-api-gateway-scale-metric"
  query: "sum(rate(container_cpu_usage_seconds_total{namespace=\"monitoring\", pod=~\"example-.*\"}[1m]))"
  threshold: "0.75"