apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cuongnvtse160875@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx  # Ensures use of the NGINX Ingress Controller