apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-api-gateway-deployment
  namespace: {{ .Values.metadata.namespace }}
  labels:
    mode: deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: websocket-api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: websocket-api-gateway
    spec:
      containers:
        - name: websocket-api-gateway
          image: {{ .Values.build.image.repository }}:{{ .Values.build.image.tag }}
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: websocket-api-gateway-env
          ports:
            - containerPort: {{ .Values.containerPort }}