
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cifarm-server-postgresql-master-persistent-volume
  namespace: default
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce 
  storageClassName: cifarm-server-postgresql-master-storage-class
  capacity:
    storage: 10Gi
  hostPath:
    path: "/mnt/volumes/cifarm-server-postgresql-master" 
    type: DirectoryOrCreate