
apiVersion: v1
kind: Pod
metadata:
  name: cifarm-server-postgres-cluster
  labels:
    app: cifarm
spec:
  initContainers:
    - name: postgresql-master
      image: bitnami/postgresql
      restartPolicy: Always
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 5
        periodSeconds: 5
      env:
        # POSTGRESQL_PGAUDIT_LOG
        - name: POSTGRESQL_PGAUDIT_LOG
          value: "READ,WRITE"

        # POSTGRESQL_LOG_HOSTNAME
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "true"

        # POSTGRESQL_REPLICATION_MODE
        - name: POSTGRESQL_REPLICATION_MODE
          value: "master"

        # POSTGRESQL_REPLICATION_USER
        - name: POSTGRESQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_REPLICATION_USER

        # POSTGRESQL_REPLICATION_PASSWORD
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_REPLICATION_PASSWORD

        # POSTGRESQL_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_PASSWORD
        
        # POSTGRESQL_DATABASE
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_DATABASE

        # POSTGRESQL_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"
      ports:
        - containerPort: 5432
      volumeMounts:
      - name: volume
        mountPath: /var/lib/volume

  containers:
    - name: postgresql-slave
      image: bitnami/postgresql
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5433"
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
            - -p
            - "5433"
        initialDelaySeconds: 5
        periodSeconds: 5
      env:
        # POSTGRESQL_PASSWORD
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_PASSWORD

        # POSTGRESQL_MASTER_HOST
        - name: POSTGRESQL_MASTER_HOST
          value: "127.0.0.1"
        
        # POSTGRESQL_PGAUDIT_LOG
        - name: POSTGRESQL_PGAUDIT_LOG
          value: "READ"

        # POSTGRESQL_LOG_HOSTNAME
        - name: POSTGRESQL_LOG_HOSTNAME
          value: "true"

        # POSTGRESQL_REPLICATION_MODE
        - name: POSTGRESQL_REPLICATION_MODE
          value: "slave"

        # POSTGRESQL_REPLICATION_USER
        - name: POSTGRESQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_REPLICATION_USER 

        # POSTGRESQL_REPLICATION_PASSWORD
        - name: POSTGRESQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cifarm-server-postgresql-master-secret
              key: POSTGRESQL_REPLICATION_PASSWORD

        # POSTGRESQL_MASTER_PORT_NUMBER
        - name: POSTGRESQL_MASTER_PORT_NUMBER
          value: "5432"
              
        # POSTGRESQL_ALLOW_EMPTY_PASSWORD
        - name: ALLOW_EMPTY_PASSWORD
          value: "no"

          # POSTGRESQL_PORT_NUMBER
        - name: POSTGRESQL_PORT_NUMBER
          value: "5433"
      ports:
        - containerPort: 5433
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: cifarm-server-postgresql-master-persistent-volume-claim