{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cifarm-system-ingress
  namespace: gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    {{- if .Values.global.ingress.tls.enabled }}
    - hosts:
        - {{ .Values.global.ingress.hostname }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
    {{- end }}
  rules:
    - host: {{ .Values.global.ingress.hostname }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rest-api-gateway
                port:
                  number: {{ .Values.restApiGateway.deployment.containerPort }}

          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graphql-api-gateway
                port:
                  number: {{ .Values.graphqlApiGateway.deployment.containerPort }}

          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: websocket-api-gateway
                port:
                  number: {{ .Values.websocketApiGateway.deployment.containerPort }}
{{- end }}
