apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  namespace: gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    # REST API Gateway
    - host: api.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: rest-api-gateway
                port:
                  number: {{ .Values.restApiGateway.deployment.containerPort }}

    # GraphQL API Gateway
    - host: api.example.com
      http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graphql-api-gateway
                port:
                  number: {{ .Values.graphqlApiGateway.deployment.containerPort }}

    # WebSocket API Gateway
    - host: api.example.com
      http:
        paths:
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: websocket-api-gateway
                port:
                  number: {{ .Values.websocketApiGateway.deployment.containerPort }}
  tls:
    - hosts:
        - api.example.com
      secretName: {{ .Values.global.ingress.tls.secretName }}
