
apiVersion: v1
kind: Pod
metadata:
  name: cifarm-periphery
  labels:
    app: cifarm
spec:
  container:
    - name: cifarm-periphery
      image: gcr.io/kaniko-project/executor:debug
      args: [
            "--context=git://github.com/starci-lab/cifarm-periphery.git",
            "--destination=starci/cifarm-periphery-dev",
            "--dockerfile=/.docker/dev/Dockerfile",
            ]
      ports:
        - containerPort: 27017