---
# Source: auth-service/templates/service-cluster-ip.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip 
  labels:
    mode: deploy
spec:
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
---
# Source: auth-service/templates/kaniko-build.yaml
apiVersion: v1
kind: Pod
metadata:
  name: auth-service-kaniko-build
  labels: 
    mode: build
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    args:
      - "--context=git://github.com/starci-lab/cifarm-containers"
      - "--destination=starci183/auth-service:latest"
      - "--dockerfile=./apps/auth-service/Dockerfile"
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
---
# Source: auth-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    mode: deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
    spec:
      containers:
        - name: auth-service
          image: starci183/auth-service:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: auth-service-env
          ports:
            - containerPort: 3005

#kubectl exec -it auth-service-deployment-67448d654f-8jrwf -- netstat -tuln
