# ClusterIP configuration
clusterIp:
  metadata:
    name: wallet-service-cluster-ip
  selector:
    name: wallet-service-selector

# Secret configuration
secret:
  metadata:
    name: wallet-service-deployment-secret
  env:
    gameplayPostgres:
      dbName: "postgres"
      host: "postgres"
      port: 5432
      user: "postgres"
      pass: "postgres"

# Deployment configuration
deployment:
  metadata:
    name: wallet-service-deployment
  args:
    image:
      repository: cifarm/wallet-service
      tag: latest
    dockerfile: ./apps/wallet-service/Dockerfile
    context: git://github.com/starci-lab/cifarm-containers
  replicaCount: 1
  containerPort: 
    port: 3008
    targetPort: 3008
  resources: 
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

# Service configuration
scaledObject:
  metadata:
    name: wallet-service-deployment-scaled-object
  minReplicaCount: 1
  maxReplicaCount: 3
  cooldownPeriod: 30                   
  pollingInterval: 5     
  trigger:
    serverAddress:
      host: 
        name: prometheus-kube-prometheus-prometheus
        namespace: monitoring
      port: 9090
    metricName: wallet-service-deployment-scaled-object_keda
    query: sum(rate(container_cpu_usage_seconds_total{namespace="monitoring", pod=~"wallet-service-.*"}[1m]))"
    threshold: "0.3"