apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-gateway-deployment
  labels:
    mode: deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rest-api-gateway
  template:
    metadata:
      name: rest-api-gateway
      labels:
        app.kubernetes.io/name: rest-api-gateway
    spec:
      containers:
        - name: rest-api-gateway
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: rest-api-gateway-env
          ports:
            - containerPort: {{ .Values.containerPort }}

#one replica - for testing
#kubectl scale deployment rest-api-gateway-deployment --replicas=1