apiVersion: v1
kind: Service
metadata:
  name: rest-api-gateway-load-balancer
  labels:
    mode: deploy
spec:
  selector:
    app.kubernetes.io/name: rest-api-gateway
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  type: LoadBalancer

#kubectl exec -it rest-api-gateway-deployment-7b9b75f985-5cps2 -- netstat -tuln