debug: true
replicaCount: 3
containerPort: 3008

metadata:
  clusterName: "websocket-api-gateway"
  namespace: "websocket-api-gateway"

build:
  image:
    repository: cifarm/websocket-api-gateway
    tag: latest